/**
 * Canonical schema for demo prediction fixtures
 *
 * This format is the single source of truth for offline demo examples.
 * Generated by tools/generate_demo_fixtures.py using real LayoutLMv3 inference.
 *
 * Schema version: demo_pred_v1
 */

/**
 * Bounding box: [x1, y1, x2, y2]
 * Coordinates are in the space specified by DemoPrediction.page.coordSpace
 */
export type BBox = [number, number, number, number];

/**
 * Token-level prediction from LayoutLMv3
 * This is the most granular level - typically word or sub-word tokens
 */
export interface DemoToken {
  /** Unique token ID within this prediction */
  id: number;
  /** Token text (word or sub-word) */
  text: string;
  /** Bounding box in page coordinate space */
  bbox: BBox;
  /** Predicted label from LayoutLMv3 */
  label: string;
  /** Model confidence score (0-1) */
  conf: number;
}

/**
 * Line-level grouping of tokens
 * Represents logical lines like "2 cups flour" or "Preheat oven to 350°F"
 */
export interface DemoLine {
  /** Unique line ID within this prediction */
  id: number;
  /** Line kind/category */
  kind: "INGREDIENT_LINE" | "INSTRUCTION_STEP" | "TITLE_LINE" | "OTHER";
  /** Union bounding box covering all tokens in this line */
  bbox: BBox;
  /** Token IDs belonging to this line */
  tokenIds: number[];
  /** Aggregated confidence (e.g., average of token confidences) */
  conf: number;
  /** Concatenated text from tokens (for convenience) */
  text?: string;
}

/**
 * Section-level regions (Title, Ingredients, Instructions)
 * These are the clean semantic overlays shown by default
 */
export interface DemoSection {
  /** Union bounding box(es) for this section */
  bbox: BBox;
  /** Line IDs belonging to this section (if derived from lines) */
  lineIds?: number[];
  /** Aggregated confidence */
  conf: number;
}

/**
 * Sections object containing all semantic regions
 */
export interface DemoSections {
  /** Title section (typically single box) */
  title?: DemoSection;
  /** Ingredients section (may be split into 1-2 boxes for columns) */
  ingredients?: DemoSection[];
  /** Instructions section (typically single box) */
  instructions?: DemoSection;
}

/**
 * Extracted recipe in structured format
 * This is what gets displayed in the recipe card
 */
export interface ExtractedRecipeV1 {
  /** Recipe title */
  title: string;
  /** List of ingredient strings (one per line) */
  ingredients: string[];
  /** List of instruction strings (one per step) */
  instructions: string[];
  /** Optional: servings, yield, time, etc. */
  servings?: string;
  yield?: string;
  prepTime?: string;
  cookTime?: string;
  /** Section-level confidence scores */
  confidence: {
    title: number;
    ingredients: number;
    instructions: number;
    overall: number;
  };
}

/**
 * Page metadata describing the coordinate space
 */
export interface PageInfo {
  /** Original image width */
  width: number;
  /** Original image height */
  height: number;
  /** Coordinate space used for all bboxes */
  coordSpace: "px" | "norm_1000";
}

/**
 * Fixture generation metadata
 */
export interface FixtureMeta {
  /** Example ID matching directory name */
  exampleId: string;
  /** Cookbook page number (if known) */
  cookbookPage?: number;
  /** Scan image filename */
  scanIndex?: number;
  /** ISO timestamp when fixture was generated */
  generatedAt: string;
  /** Model checkpoint used for inference */
  modelId?: string;
  /** OCR engine used */
  ocrEngine?: string;
}

/**
 * Complete demo prediction (single source of truth)
 *
 * Generated offline by running LayoutLMv3 inference on demo scan images.
 * Bundled with the frontend repo for network-free demo experience.
 */
export interface DemoPrediction {
  /** Schema version for future compatibility */
  schemaVersion: "demo_pred_v1";

  /** Page dimensions and coordinate space */
  page: PageInfo;

  /** Token-level predictions (most granular) */
  tokens: DemoToken[];

  /** Line-level groupings */
  lines: DemoLine[];

  /** Section-level regions (for clean overlays) */
  sections: DemoSections;

  /** Extracted recipe (final structured output) */
  extractedRecipe: ExtractedRecipeV1;

  /** Generation metadata */
  meta: FixtureMeta;
}

/**
 * Legacy compatibility: map old ExtractedRecipe to new format
 * Used during migration period
 */
export function migrateExtractedRecipe(old: any): ExtractedRecipeV1 {
  return {
    title: old.title || "",
    ingredients: old.ingredients || [],
    instructions: old.instructions || [],
    servings: old.servings,
    yield: old.yield,
    prepTime: old.prep_time,
    cookTime: old.cook_time,
    confidence: old.confidence || {
      title: 0.9,
      ingredients: 0.9,
      instructions: 0.9,
      overall: 0.9,
    },
  };
}

/**
 * Convert DemoPrediction tokens to RecipeToken format (for overlay viewers)
 */
export function tokensToRecipeTokens(prediction: DemoPrediction): Array<{
  id: string;
  text: string;
  label: string;
  score: number;
  bbox: BBox;
}> {
  return prediction.tokens.map((t) => ({
    id: `tok-${t.id}`,
    text: t.text,
    label: t.label,
    score: t.conf,
    bbox: t.bbox,
  }));
}

/**
 * Convert DemoPrediction lines to RecipeToken format (for line-level overlays)
 */
export function linesToRecipeTokens(prediction: DemoPrediction): Array<{
  id: string;
  text: string;
  label: string;
  score: number;
  bbox: BBox;
}> {
  return prediction.lines.map((line) => ({
    id: `line-${line.id}`,
    text: line.text || prediction.tokens
      .filter((t) => line.tokenIds.includes(t.id))
      .map((t) => t.text)
      .join(" "),
    label: line.kind,
    score: line.conf,
    bbox: line.bbox,
  }));
}
